name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

jobs:
  test:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env: ["dev", "built"]
        builder: ["vite"]
        context: ["async", "default"]
        payload: ["json", "js"]
        node: ["lts"]
        exclude:
          - context: "default"
            payload: "js"

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ inputs.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install
        run: pnpm i

      - name: Install Playwright Browsers
        run: |
          pnpm playwright-core install chromium
          pnpm playwright-core install firefox

      - name: Prepare dev environment
        run: pnpm run dev:prepare

      - name: Test
        run: pnpm run test
